import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import {getLocale, getMessages} from "next-intl/server";
import {AppProvider} from "@/app/providers";
import {ReactNode} from "react";
import {NextIntlClientProvider} from "next-intl";
import {Header} from "@/shared/components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "sekaianime",
    description: "Generated by create next app",
};

export default async function AnimeLayout({children}: Readonly<{ children: ReactNode; }>) {
    const locale = await getLocale();
    const messages = await getMessages();
    return (
        <html lang={locale} suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            <AppProvider>
                <Header/>
                <main className={'flex flex-col max-w-[1200px] mx-auto overflow-y-scroll'}>{children}</main>
            </AppProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
